import Head from 'next/head'
import Image from 'next/image'
import Calculations from '../components/dashboard/Calculations'
import Dashboard from '../components/dashboard/Dashboard'
import Layout from '../components/layout/Layout'

export default function Index() {
  return (
    <div>
      <Head>
        <title>Supermetrics Assignment</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout>
        <h1>Dashboard page</h1>
        <Calculations />
      </Layout>

      <footer>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
